#!/usr/bin/env bash

## Copyright (C) 2023 Ticks <ticks.cc@gmail.com>
##
## Launch term in hyprland
##

DIR="${HOME}/.config/hypr"
CONFIG="${DIR}/term/alacritty/alacritty.toml"

if [ "$1" == "--float" ]; then
	alacritty --class "alacritty-float,alacritty-float" --config-file "${CONFIG}"
elif [ "$1" == "--full" ]; then
	alacritty --class "Fullscreen,Fullscreen" --config-file "${CONFIG}" \
		-o window.startup_mode=fullscreen \
		window.padding.x=20 window.padding.y=20 \
		window.opacity=0.95
else
	alacritty --config-file "${CONFIG}"
fi
