#!/usr/bin/env bash

## Copyright (C) 2023 Ticks <ticks.cc@gmail.com>
##
## Lockscreen with current theme background
##

DIR="${HOME}/.config/hypr"

if [ -e "${DIR}/.current" ]; then
	source "${DIR}/.current"
else
	source "${DIR}/custom/theme.sh"
fi

wp="${wallpaper_path}"

if [ -e "$wp" ]; then
	swaylock -i "$wp"
else
	swaylock --color '#23273a'
fi
