## Copyright (C) 2023 Ticks <ticks.cc@gmail.com>
##
## See more at /usr/share/doc/alacritty/example/alacritty.toml
##

## Import files (Colors, Fonts, Etc)
## 导入其他配置文件
import=["~/.config/hypr/term/alacritty/colors.toml", "~/.config/hypr/term/alacritty/fonts.toml"]

## Live config reload
## 自动刷新配置文件
live_config_reload=true
## 启动目录
# working_directory: None

## Set environment variables
## 设置环境变量
[env]
TERM="alacritty"

## Terminal window settings
## 窗口设置
[window]
## 窗口修饰，full: 有边框+标题栏，none: 无边框+标题栏
decorations="none"
## 启动模式 (Fullscreen, Maximized, Windowed)
startup_mode="Windowed"
## 动态窗口标题
dynamic_title=true
## Background opacity
## 背景透明度 
opacity=1.0
## 模糊效果
blur=true

[window.dimensions]
## 窗口行数与列数
columns=82
lines=23

[window.padding]
x=10
y=10

[scrolling]
## 历史记录行数
history=5000
## 每次滚动行数
multiplier=5

[cursor]
## 当窗口未聚焦时，光标是否显示为空心框
unfocused_hollow=false
[cursor.style]
## 光标样式 ( ▇ Block, _ Underline, | Beam)
shape="Block"
## 光标闪烁
blinking="On"

[debug]
log_level="Error"
print_events=false
render_timer=false