# Default colors
[colors.primary]
background="#121015"
foreground="#cfd1da"
dim_foreground="#cfd1da"
bright_foreground="#cfd1da"

# Cursor colors
[colors.cursor]
text="#121015"
cursor="#cfd1da"

[colors.vi_mode_cursor]
text="#121015"
cursor="#316F85"

# Search colors
[colors.search]
matches.foreground="#121015"
matches.background="#909298"
focused_match.foreground="#121015"
focused_match.background="#316F85"

[colors.footer_bar]
foreground="#121015"
background="#909298"

# Selection colors
[colors.selection]
text="#121015"
background="#677491"

# Normal colors
[colors.normal]
black="#121015"
red="#E4887B"
green="#316F85"
yellow="#677491"
blue="#A17886"
magenta="#738BAC"
cyan="#E09997"
white="#cfd1da"

# Bright colors
[colors.bright]
black="#909298"
red="#E4887B"
green="#316F85"
yellow="#677491"
blue="#A17886"
magenta="#738BAC"
cyan="#E09997"
white="#cfd1da"

# Dim colors
[colors.dim]
black="#909298"
red="#E4887B"
green="#316F85"
yellow="#677491"
blue="#A17886"
magenta="#738BAC"
cyan="#E09997"
white="#cfd1da"

