# Default colors
[colors.primary]
background="#f8faf0"
foreground="#191d17"
dim_foreground="#191d17"
bright_foreground="#191d17"

# Cursor colors
[colors.cursor]
text="#f8faf0"
cursor="#191d17"

[colors.vi_mode_cursor]
text="#f8faf0"
cursor="#191d17"

# Search colors
[colors.search]
matches.foreground="#191d17"
matches.background="#ecefe5"
focused_match.foreground="#ecefe5"
focused_match.background="#191d17"

[colors.footer_bar]
foreground="#191d17"
background="#f8faf0"

# Selection colors
[colors.selection]
text="#f8faf0"
background="#191d17"

# Normal colors
[colors.normal]
black="#11111b"
red="#d20f39"
green="#40a02b"
yellow="#df8e1d"
blue="#1e66f5"
magenta="#8839ef"
cyan="#9ca0b0"
white="#eff1f5"

# Bright colors
[colors.bright]
black="#11111b"
red="#d20f39"
green="#40a02b"
yellow="#df8e1d"
blue="#1e66f5"
magenta="#8839ef"
cyan="#9ca0b0"
white="#eff1f5"

# Dim colors
[colors.dim]
black="#11111b"
red="#d20f39"
green="#40a02b"
yellow="#df8e1d"
blue="#1e66f5"
magenta="#8839ef"
cyan="#9ca0b0"
white="#eff1f5"
