## Copyright (C) 2023 Ticks <ticks.cc@gmail.com>
##
## Font configuration for alacritty
##

# Normal font face
[font.normal]
family="Maple Mono SC NF"
# Bold font face
[font.bold]
family="Maple Mono SC NF"
# Italic font face
[font.italic]
family="Maple Mono SC NF"
# Bold italic font face
[font.bold_italic]
family="Maple Mono SC NF"
[font]
# Point size
size=14


